### ISSUE TITLE
warnings with VS2022 Version 17.5.3

### ISSUE THREAD

**Issue by spudwa** [gigasopht/iplusplus#1]
There are several warnings issued with the latest version of Visual Studio. Also I suggest you increase the warnings to level 4 as this shows some other potential problems and performance improvements using constexpr. Thanks

**Comment by gigasopht** [comment]
Ok I'll have another look at the code[; although, it is 15 years behind where I am working at present.

**Comment by gigasopht** [comment]
The warning have been reduced to just 3.
