### ISSUE TITLE
wchar_t to std:conversion

### ISSUE THREAD

**Issue by spudwa** [gigasopht/iplusplus#2]
Well I decided to use this project to learn a bit more about modules and while most warnings are trivial or because of lack of compiler support, the last warnings is in this function

export inline  iarchive& operator>>(iarchive& s, std::string& o) in which you 'convert' a wchar_t to std::string. There are lots of solutions but they all depend on UNICODE or utf_16 but the possibility of data loss seems high. I'm not sure what your trying to achieve

**Comment by spudwa** [comment]
Thanks for the clarification. One of the reasons I like W4 and warnings as errors is it forces me to look at suspect conversions and if I'm happy that I'm right and the the compiler is wrong I'll add a cast or even a pragma to keep the compile clean

**Comment by gigasopht** [comment]
I actually made a mistake at that point. It now has been corrected in github.
