### ISSUE TITLE
layer has wrong project type

### ISSUE THREAD

**Issue by spudwa** [gigasopht/iplusplus#3]
<ConfigurationType>Application</ConfigurationType>

should be DLL

**Comment by gigasopht** [comment]
I can't find the application type on github. In the application itself it has dll as the type.

**Comment by spudwa** [comment]
Application type is set in the project file of Visual Studio. I'm have great difficulty building and of the code. What toolchain are you using

**Comment by spudwa** [comment]
layer.dll has a dependency on iccW.def but the file is actually called icc.def
